apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - image: nvidia/cuda
      name: gpu-pod
      command:
      - nvidia-smi
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
