groups:
  - name: worker node alert
    rules:
    - alert: Node
      expr: up{job="worker node"} == 0
      for: 1m
      labels:
        severity: Fatal
      annotations:
        description: "{{ $labels.instance }} 无法连接"
    - alert: Memory
      expr: (1-node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)*100 > 85
      for: 3m
      labels:
        severity: Warning
      annotations:
        description: "{{ $labels.instance }} 内存使用率{{ $value }}% "
    - alert: CPU
      expr: avg(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance) * 100  < 10
      for: 3m
      labels:
        severity: Warning
      annotations:
        description: "{{ $labels.instance }} CPU使用率{{ $value }}% "
    - alert: Disk
      expr: avg(1-node_filesystem_avail_bytes{mountpoint !~ "/var.*"}/node_filesystem_size_bytes{mountpoint !~ "/var.*"}) by (instance) > 85
      for: 3m
      labels:
        severity: Warning
      annotations:
        description: "{{ $labels.instance }} 磁盘使用率{{ $value }}% "
  - name: business alert
    rules:
    - alert: apache2
      expr: up{job="business api"} == 0
      for: 1m
      labels:
        severity: Warning
      annotations:
        description: "{{ $labels.instance }} 无法连接 "
