apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik
        imagePullPolicy: IfNotPresent
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
          hostPort: 8080
        volumeMounts:
        - name: config
          mountPath: /traefik_ssl/config/
        - name: tls
          mountPath: /traefik_ssl/tls/
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --configfile=/traefik_ssl/config/traefik.conf
      volumes:
      - name: config
        configMap:
          name: traefik-config
      - name: tls
        secret:
          secretName: traefik-tls
