#!/bin/bash
cfssl gencert -initca ca-csr.json | cfssljson -bare ca -
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=www server.json | cfssljson -bare server

kubectl create secret tls ingress-grafana-secret --key server-key.pem  --cert server.pem
